In [2]:
#import numpy
import numpy as np

#initialize a numpy array
arr = np.array([-1,2,5], dtype = np.float32)
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


In [3]:
#creates a 2D_matrix
arr = np.array([[1,2,3], [4,5,6]], dtype = np.float32)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
#upcasting numpy upcast to the highest level type
arr = np.array([2,8,0.89,3.4])
print(arr)

[2.   8.   0.89 3.4 ]


In [5]:
arr = np.array([2, 8, 9, "english"])
print(arr)

['2' '8' '9' 'english']


In [6]:
#NaN only takes strings
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: cannot convert float NaN to integer

In [8]:
#array from a list of integers and np.nan
#as the first element and 2 to 5 inclusive as the second four elements
arr = np.array([np.nan, 2,3,4,5])
#copy arr to array2
array2 = arr.copy()
array2[0] = 10
print(repr(array2))

array([10.,  2.,  3.,  4.,  5.])


In [13]:
#Set float_arr equal to np.array applied to a list with elements 1, 5.4, and 3, in that order.

#Set float_arr2 equal to arr2.astype, with argument np.float32.

float_arr = np.array([1,5.4,3])
float_arr2 = float_arr.astype(np.float32)
print(repr(float_arr2))

array([1. , 5.4, 3. ], dtype=float32)


In [16]:
#multi-dimensional array, specifically a 2-D matrix
matrix = np.array([[1,2,3,], [4,5,6]], dtype = np.float32)
print(repr(matrix))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)


In [17]:
#np.arange
arr = np.arange(5)
print(repr(arr))
arr2 = np.arange(5, 9)
print(repr(arr2))

array([0, 1, 2, 3, 4])
array([5, 6, 7, 8])


In [20]:
#specify the number of elements in the returned array, 
arr = np.linspace(5,15, num = 6)
print(repr(arr))
arr2 = np.linspace(6, 16)
print(repr(arr2))

array([ 5.,  7.,  9., 11., 13., 15.])
array([ 6.        ,  6.20408163,  6.40816327,  6.6122449 ,  6.81632653,
        7.02040816,  7.2244898 ,  7.42857143,  7.63265306,  7.83673469,
        8.04081633,  8.24489796,  8.44897959,  8.65306122,  8.85714286,
        9.06122449,  9.26530612,  9.46938776,  9.67346939,  9.87755102,
       10.08163265, 10.28571429, 10.48979592, 10.69387755, 10.89795918,
       11.10204082, 11.30612245, 11.51020408, 11.71428571, 11.91836735,
       12.12244898, 12.32653061, 12.53061224, 12.73469388, 12.93877551,
       13.14285714, 13.34693878, 13.55102041, 13.75510204, 13.95918367,
       14.16326531, 14.36734694, 14.57142857, 14.7755102 , 14.97959184,
       15.18367347, 15.3877551 , 15.59183673, 15.79591837, 16.        ])


In [26]:
#set arr equal to np.arange with 12 as the only argument.

#set reshaped equal to np.reshape with arr as the first argument and (2, 3, 2) as the second argument.

arr = np.arange(12)
print(arr)
arr2 = np.reshape(arr, (2,3,2))
print(arr2)
flattened = arr2.flatten()
transposed = np.transpose(arr2, axes = (1,2,0))
print(flattened)
print(transposed)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  6]
  [ 1  7]]

 [[ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]]]


In [28]:
zeros_arr = np.zeros(5)
ones_arr = np.ones_like(transposed)
print(zeros_arr)
print(ones_arr)

[0. 0. 0. 0. 0.]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [29]:
#maths perations
arr = np.array([[1,2], [3,4]])
print(repr(arr + 1))

array([[2, 3],
       [4, 5]])


In [30]:
arr = np.array([[1, 2], [3, 4]])
# Add 1 to element values
print(repr(arr + 1))
# Subtract element values by 1.2
print(repr(arr - 1.2))
# Double element values
print(repr(arr * 2))
# Halve element values
print(repr(arr / 2))
# Integer division (half)
print(repr(arr // 2))
# Square element values
print(repr(arr**2))
# Square root element values
print(repr(arr**0.5))

array([[2, 3],
       [4, 5]])
array([[-0.2,  0.8],
       [ 1.8,  2.8]])
array([[2, 4],
       [6, 8]])
array([[0.5, 1. ],
       [1.5, 2. ]])
array([[0, 1],
       [1, 2]])
array([[ 1,  4],
       [ 9, 16]])
array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])


In [31]:
arr = np.array([[-0.5,0.8,-0.1], [0.0,-1.2,1.3]])
arr2 = np.array([[1.2,3.1], [1.2,0.3], [1.5,2.2]])
print(arr)
print(arr2)
multiplied = arr * np.pi
added = (arr + multiplied)
squared = added **2
print(multiplied)
print(added)
print(squared)
exponential = np.exp(squared)
logged = np.log(arr2)
print(exponential)
print(logged)


[[-0.5  0.8 -0.1]
 [ 0.  -1.2  1.3]]
[[1.2 3.1]
 [1.2 0.3]
 [1.5 2.2]]
[[-1.57079633  2.51327412 -0.31415927]
 [ 0.         -3.76991118  4.08407045]]
[[-2.07079633  3.31327412 -0.41415927]
 [ 0.         -4.96991118  5.38407045]]
[[ 4.28819743 10.97778541  0.1715279 ]
 [ 0.         24.70001718 28.98821461]]
[[7.28350596e+01 5.85587272e+04 1.18711726e+00]
 [1.00000000e+00 5.33434578e+10 3.88527393e+12]]
[[ 0.18232156  1.13140211]
 [ 0.18232156 -1.2039728 ]
 [ 0.40546511  0.78845736]]


In [32]:
matmul1 = np.matmul(logged, exponential)
matmul2 = np.matmul(exponential, logged)
print(matmul1)
print(matmul2)

[[ 1.44108036e+01  6.03529115e+10  4.39580713e+12]
 [ 1.20754286e+01 -6.42240618e+10 -4.67776415e+12]
 [ 3.03205327e+01  4.20590657e+10  3.06337283e+12]]
[[ 1.06902790e+04 -7.04197733e+04]
 [ 1.58506868e+12  2.99914875e+12]]


In [33]:
#Set random1 equal to np.random.randint with 5 as the only argument.

#set random_arr equal to np.random.randint with 3 as the first argument, 10 as the high keyword argument, and (3, 5) as the size keyword argument\

random1 = np.random.randint(5)
random_arr = np.random.randint(3, high = 10, size = (3,5))
print(random1)
print(random_arr)

3
[[6 3 9 5 6]
 [8 8 6 4 8]
 [3 6 3 6 5]]


In [34]:
choices = ["a", "b", "c", "d"]
choice = np.random.choice(choices, p = [0.5, 0.1, 0.2, 0.2])
print(choice)

a


In [35]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[1 3 2 4 5]
